
theme: jekyll-theme-cayman
title: JYWT38
description: "2022"
encoding: UTF-8
future: true
jailed: false

github: [metadata]
  is_project_page: false

gfm_quirks: paragraph_end
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  input: GFM
  hard_wrap: false
plugins:
   - jekyll-coffeescript
   - jekyll-gist
   - jekyll-github-metadata
   - jekyll-paginate
   - jekyll-relative-links
   - jekyll-optional-front-matter
   - jekyll-readme-index
   - jekyll-default-layout
   - jekyll-titles-from-headings
   - jekyll-feed
   - jekyll-redirect-from
   - jekyll-seo-tag
   - jekyll-sitemap
   - jekyll-avatar
   - jemoji
   - jekyll-mentions
   - jekyll-include-cache
